services:
  nop-mysql:
    image: mariadb:11.8
    container_name: nop-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: nopcommerce
      MARIADB_USER: nop
      MARIADB_PASSWORD: nop123
      MARIADB_ROOT_PASSWORD: root123
    command: ["mariadbd", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--skip-log-bin"]
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u nop -pnop123 -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
